:source-highlighter: highlightjs
:highlightjs-theme: agate

ifdef::env-github[]
:imagesdir: images/
endif::[]

== Starting from scratch, again.

We show what you can get after some experimenting. We present it as if it was what
we had from the start, be in actuality we arrive here by applying refactoring on the architecture.

In all diagrams below, the [blue]`Customer` class is the stand in for all possible entities, so Flight, Airport, Ticket etc.

Looking at the intermezzo in https://prc2.fontysvenlo.org/2021/week07.html#_currywurst_is_not_made_of_steel_and_vice_versa[Sausage and Machines ^],
we realize that we have sausage Customer and machine CustomerManager. In a serious conversation you would use entities and System as the official terms.

=== The start, Business and data

Start with Data (entities) and the system (part) that deals with it.

.Start, revised class diagram.
image::AISClassDiagram1a.svg[opts=inline]

=== Adding GUI, but unconnected.

.GUI and System, revised class diagram.
image::AISClassDiagram2a.svg[]

=== Connect GUI and Business Logic with Assembler

.Assembler, revised class diagram.
image::AISClassDiagram3a.svg[]


=== Adding persistence, which are now external but reusable components.

Adding persistence is easy if you have *libraries* that do the work. You implemented one in week 6 and 7 in PRC2.
Do not add these components into the project, but instead add them as dependencies in the appropriate places in the AIS system.

One advantage of using a library is that you do not have to test it, because you may assume that the provider of the library tested it. +
[big]_You did, didn't you?_

.Final, revised class diagram.
image::AISClassDiagram4a.svg[]

== Summarizing the whole as a sequence of operations.

.The conceptual order of operations.
image:sequencediagram.svg[]


=== Using the generic dao as persistence implementation.

.A use of the DAO.
[source,java]
----
public class CustomerBusiness {

    final DAOFactory daoFactory ;
    // injection done by assembler
    public CustomerBusiness( DAOFactory aFactory ) {
        this.daoFactory = aFactory;
    }

    /**
     * Get all customers named Jan.
     */
    void sampleMethod() {
        var customerDao = daoFactory.createDao( Customer.class);
        List<Customer> allJans =  customerDao.getByColumnValues( "firstname", "Jan");

    }
}
----

.Simple Customer entity
[source,java]
----
public class Customer implements Serializable {

    @ID
    private final Integer customerid;
    private final String firstname;
    private final String lastname;

    public Customer( Integer customerid, String firstname, String lastname ) {
        this.customerid = customerid;
        this.firstname = firstname;
        this.lastname = lastname;
    }

    public Integer getCustomerid() {
        return customerid;
    }

    public String getFirstname() {
        return firstname;
    }

    public String getLastname() {
        return lastname;
    }

}
----

.Mapper generated by generateentitymappers script from genericmapper project
[source,java]
----
package daoclient;

import daoclient.Customer;
import genericmapper.Mapper;
import java.util.function.Function;

/**
 * Generated code. Do not edit, your changes will be lost.
 */
public class CustomerMapper extends Mapper<Customer, Integer> {

    // No public ctor
    private CustomerMapper() {
        super( Customer.class, java.lang.invoke.MethodHandles.lookup()  );
    }

    // self register
    static {
        Mapper.register( new CustomerMapper() );
    }

    // the method that it is all about
    @Override
    public Object[] deconstruct(  Customer c ) {
           return new Object[]{
                            c.getCustomerid(),
              c.getFirstname(),
              c.getLastname()
           };
    }

    @Override
    public Function<Customer, Integer> keyExtractor() {
        return ( Customer c ) -> c.getCustomerid();
    }

    @Override
    public Class<Integer> keyType() {
        return Integer.class;

    }
}
----

An up to date version of the (code stripped) version of the genericmapper and genericdao combined with the required changes for
the mapper plugin can be found at https://github.com/sebivenlo/mapperplugin[github sebivenlo mapper plugin].
